FROM node:18-alpine

WORKDIR /app

ENV NODE_ENV=development
ENV PORT=3001

COPY package*.json ./
RUN npm ci

COPY tsconfig.json ./
COPY src ./src
COPY config ./config

EXPOSE 3001

CMD ["npm", "run", "start:dev"]
